CSS = {
    'CSS | 1. Kirish': "BAACAgIAAxkBAAIBC2IcaIgz9yaCyx1WPMPnNy7dHTuoAAJTDgACStCgSolESfMayjQ1IwQ",
    'CSS | 2. CSS haqida. Kurs loyihasi': "BAACAgIAAxkBAAIBDWIcaKgQCRBOULXI0b9ERmQd_tWyAAIBGAACEjcgSqJXvQLaVL2yIwQ",
    'CSS | 3. HTML hujjat va CSS. Loyiha strukturasi': "BAACAgIAAxkBAAIBD2IcaMR1guaFOmiFmBURdCHAh1rEAAIDFQACu20pSoDNo6nc3XNmIwQ",
    'CSS | 4. Selectors (Tanlab oluvchilar)': "BAACAgIAAxkBAAIBEWIcaObUzC3ZTCODVMTxbZqT4xiEAAImFgACNCagSgMgxs0O4s_-IwQ",
    'CSS | 5. Comments (Izohlar)': "BAACAgIAAxkBAAIBE2IcaQQsbhvWigXRrWK8vzL_hdImAAJLGAACdXqYSkVDIDQCtVkjIwQ",
    'CSS | 6. Specificity (O\'ziga xoslik)': "BAACAgIAAxkBAAIBFWIcaYrvNkdWPXPasHq3Nt3s1ahrAAI1EgACWwmhSpRL16GzcWy1IwQ",
    'CSS | 7. Inheritance (Meros olish)': "BAACAgIAAxkBAAIBF2IcalQ2KB06fZremShzlpx-BCw1AALWFAACdiagSn4XQwElf_wkIwQ",
    'CSS | 8. Combinators (Kombinatorlar)': "BAACAgIAAxkBAAIBGWIcan1ye8gRwSYf6mjd8lY_z1_UAAKuFAACuOCgSr1dlkWbu6vqIwQ",
    'CSS | 9. "Class"lar va qo\'shma (combined) selektorlar': "BAACAgIAAxkBAAIBG2Icaq1PuTtbTvPBKzBbEgOXAhGoAAImFQACdNShSsBueoHOiHU0IwQ",
    'CSS | 10. Class yoki ID. "!important" haqida': "BAACAgIAAxkBAAIBHWIcastTT9iIPimFSU7OipycsaBnAAKJEwACELegSpsqTFFip6eLIwQ",
    'CSS | 11. CSS asoslari yordamida loyihani yaxshilash': "BAACAgIAAxkBAAIBH2IcaukxObcWg5mcKjgOKfCA8S9sAALOEQACRjOgSoKavIy7cyzeIwQ",
    'CSS | 12. Box model (Quti modeli). Margin, Padding, Border': "BAACAgIAAxkBAAIBIWIcawVTG2GTkZOpuDp-RhR8DPvCAAIiDQACStCgSvPadv-8ST1DIwQ",
    'CSS | 13. Margin collapsing. Shorthands (Qisqartmalar)': "BAACAgIAAxkBAAIBI2Icax88x826rLVbm1AgojtwDvk8AAK_GQACLCExS77ouAIMvMPdIwQ",
    'CSS | 14. Height (balandlik), Width (kenglik). Max / Min - height / width': "BAACAgIAAxkBAAIBJWIcaz0RcXB73AOouvky_0MlhP-kAAKXGgACFk8xS9dsThPP_b1jIwQ",
    'CSS | 15. "Display" xossasi': "BAACAgIAAxkBAAIBJ2Ica3WvSaZgQG7EITYFyBEGmIvMAALAGQACLCExSzp7BQhDW_xgIwQ",
    'CSS | 16. Text align, Vertical align va Float': "BAACAgIAAxkBAAIBKmIca5Kluv3toGkuYAIGlky9ERkpAAKYGgACFk8xS4KJ9HBUGil3IwQ",
    'CSS | 17. Text decoration. Pseudo classes va qoidalarni guruhlash': "BAACAgIAAxkBAAIBLGIca70jIojbeX7hky42sDfya1kEAAI3EwACxycwS0I4VkRQFA7XIwQ",
    'CSS | 18. Asosiy xossalar yordamida loyihani yaxshilash (1-qism)': "BAACAgIAAxkBAAIBLGIca70jIojbeX7hky42sDfya1kEAAI3EwACxycwS0I4VkRQFA7XIwQ",
    'CSS | 19. Asosiy xossalar yordamida loyihani yaxshilash (2-qism)': "BAACAgIAAxkBAAIBLmIca_r_sWJeSaQIoGTvvcvYOnanAALaEQACYUFZSxASSst9B3egIwQ",
    'CSS | 20. Asosiy xossalar yordamida loyihani yaxshilash (3-qism)': "BAACAgIAAxkBAAIBMGIcbBZUFJb4QpYamWTGLt6bXUcbAALrGAACC4EpSjTZBPuHW0xuIwQ",
    'CSS | 21. Joylashish va "static" qiymati': "BAACAgIAAxkBAAIBM2IcbEO-3JVzjq2MAzHMYz4a6qyfAALvFgACOqIJS_1otW8JTFNzIwQ",
    'CSS | 22. Relative va Fixed': "BAACAgIAAxkBAAIBNWIcbGL3HyzXu51CSeWTFFMuzSHVAAIkFAACP2lRS2EnJ9LYo367IwQ",
    'CSS | 23. Absolute va Sticky': "BAACAgIAAxkBAAIBN2IcbH1Avce-KFHdXtics_zA4gYkAALxFgAC-wMRS8g-kvjQHPxZIwQ",
    'CSS | 24. Z-index va Overflow': "BAACAgIAAxkBAAIBOWIcbJmrrjFFZ17_XO3nund-Lhg5AAIqEgACXiUQSyMQg93zdfQ8IwQ",

}