CSS = {
    'CSS | 1. Kirish': "BAACAgIAAxkBAAIBC2IcaIgz9yaCyx1WPMPnNy7dHTuoAAJTDgACStCgSolESfMayjQ1IwQ",
    'CSS | 2. CSS haqida. Kurs loyihasi': "BAACAgIAAxkBAAIBDWIcaKgQCRBOULXI0b9ERmQd_tWyAAIBGAACEjcgSqJXvQLaVL2yIwQ",
    'CSS | 3. HTML hujjat va CSS. Loyiha strukturasi': "BAACAgIAAxkBAAIBD2IcaMR1guaFOmiFmBURdCHAh1rEAAIDFQACu20pSoDNo6nc3XNmIwQ",
    'CSS | 4. Selectors (Tanlab oluvchilar)': "BAACAgIAAxkBAAIBEWIcaObUzC3ZTCODVMTxbZqT4xiEAAImFgACNCagSgMgxs0O4s_-IwQ",
    'CSS | 5. Comments (Izohlar)': "BAACAgIAAxkBAAIBE2IcaQQsbhvWigXRrWK8vzL_hdImAAJLGAACdXqYSkVDIDQCtVkjIwQ",
    'CSS | 6. Specificity (O\'ziga xoslik)': "BAACAgIAAxkBAAIBFWIcaYrvNkdWPXPasHq3Nt3s1ahrAAI1EgACWwmhSpRL16GzcWy1IwQ",
    'CSS | 7. Inheritance (Meros olish)': "BAACAgIAAxkBAAIBF2IcalQ2KB06fZremShzlpx-BCw1AALWFAACdiagSn4XQwElf_wkIwQ",
    'CSS | 8. Combinators (Kombinatorlar)': "BAACAgIAAxkBAAIBGWIcan1ye8gRwSYf6mjd8lY_z1_UAAKuFAACuOCgSr1dlkWbu6vqIwQ",
    'CSS | 9. "Class"lar va qo\'shma (combined) selektorlar': "BAACAgIAAxkBAAIBG2Icaq1PuTtbTvPBKzBbEgOXAhGoAAImFQACdNShSsBueoHOiHU0IwQ",
    'CSS | 10. Class yoki ID. "!important" haqida': "BAACAgIAAxkBAAIBHWIcastTT9iIPimFSU7OipycsaBnAAKJEwACELegSpsqTFFip6eLIwQ",
    'CSS | 11. CSS asoslari yordamida loyihani yaxshilash': "BAACAgIAAxkBAAIBH2IcaukxObcWg5mcKjgOKfCA8S9sAALOEQACRjOgSoKavIy7cyzeIwQ",
    'CSS | 12. Box model (Quti modeli). Margin, Padding, Border': "BAACAgIAAxkBAAIBIWIcawVTG2GTkZOpuDp-RhR8DPvCAAIiDQACStCgSvPadv-8ST1DIwQ",
    'CSS | 13. Margin collapsing. Shorthands (Qisqartmalar)': "BAACAgIAAxkBAAIBI2Icax88x826rLVbm1AgojtwDvk8AAK_GQACLCExS77ouAIMvMPdIwQ",
    'CSS | 14. Height (balandlik), Width (kenglik). Max / Min - height / width': "BAACAgIAAxkBAAIBJWIcaz0RcXB73AOouvky_0MlhP-kAAKXGgACFk8xS9dsThPP_b1jIwQ",
    'CSS | 15. "Display" xossasi': "BAACAgIAAxkBAAIBJ2Ica3WvSaZgQG7EITYFyBEGmIvMAALAGQACLCExSzp7BQhDW_xgIwQ",
    'CSS | 16. Text align, Vertical align va Float': "BAACAgIAAxkBAAIBKmIca5Kluv3toGkuYAIGlky9ERkpAAKYGgACFk8xS4KJ9HBUGil3IwQ",
    'CSS | 17. Text decoration. Pseudo classes va qoidalarni guruhlash': "BAACAgIAAxkBAAIBLGIca70jIojbeX7hky42sDfya1kEAAI3EwACxycwS0I4VkRQFA7XIwQ",
    'CSS | 18. Asosiy xossalar yordamida loyihani yaxshilash (1-qism)': "BAACAgIAAxkBAAIBLGIca70jIojbeX7hky42sDfya1kEAAI3EwACxycwS0I4VkRQFA7XIwQ",
    'CSS | 19. Asosiy xossalar yordamida loyihani yaxshilash (2-qism)': "BAACAgIAAxkBAAIBLmIca_r_sWJeSaQIoGTvvcvYOnanAALaEQACYUFZSxASSst9B3egIwQ",
    'CSS | 20. Asosiy xossalar yordamida loyihani yaxshilash (3-qism)': "BAACAgIAAxkBAAIBMGIcbBZUFJb4QpYamWTGLt6bXUcbAALrGAACC4EpSjTZBPuHW0xuIwQ",
    'CSS | 21. Joylashish va "static" qiymati': "BAACAgIAAxkBAAIBM2IcbEO-3JVzjq2MAzHMYz4a6qyfAALvFgACOqIJS_1otW8JTFNzIwQ",
    'CSS | 22. Relative va Fixed': "BAACAgIAAxkBAAIBNWIcbGL3HyzXu51CSeWTFFMuzSHVAAIkFAACP2lRS2EnJ9LYo367IwQ",
    'CSS | 23. Absolute va Sticky': "BAACAgIAAxkBAAIBN2IcbH1Avce-KFHdXtics_zA4gYkAALxFgAC-wMRS8g-kvjQHPxZIwQ",
    'CSS | 24. Z-index va Overflow': "BAACAgIAAxkBAAIBOWIcbJmrrjFFZ17_XO3nund-Lhg5AAIqEgACXiUQSyMQg93zdfQ8IwQ",
    'CSS | 25. Positioning yordamida loyihani yaxshilash':'BAACAgIAAxkBAAIEGWIfD4j7Kfj2NNeHm3pQ2poWrZ6sAAKsFQACEfgIS3t5e9U_iyAcIwQ',
    'CSS | 26. Background':"BAACAgIAAxkBAAIEG2IfECu437mknFpwj8DnNXt2_-lhAALzFQACRm-5S3bPXwnutcJvIwQ",
    'CSS | 27. Styling images':'BAACAgIAAxkBAAIEHWIfEFrtrcelQcBykS0_V2MKwRZMAALGFwACmja5S-xnjMCt0E__IwQ',
    'CSS | 28. Gradient va Filterlar':'BAACAgIAAxkBAAIEH2IfEIiGBTp_y7Y0MwOHxIyclrBQAAJGFwAC1TURS-eAkG_WxCpQIwQ',
    'CSS | 29. Rasmlar (images) yordamida loyihani yaxshilash':'BAACAgIAAxkBAAIEIWIfETY3Fro1MjPLaLgX3IZOLUXFAAJVFwAC-wMRSzDvAZZVTtMSIwQ',
    'CSS | 30. Formalarga style berish (1-qism)':'BAACAgIAAxkBAAIEI2IfEWTPSu-NgoTNegZHhTODYp_aAAJkFwACrr05S0dWrsnnO1X3IwQ',
    'CSS | 31. Formalarga style berish (2-qism)':'BAACAgIAAxkBAAIEJWIfEavD5TZdFNWR0CxzhGr2hrSAAAJjFgACAbs5S_4Gi6ipE9PdIwQ',
    'CSS | 32. Formalar yordamida loyihani yaxshilash':'BAACAgIAAxkBAAIEJ2IfEdAqtadCqU80app0alGANRvMAALDEgACSffBS4Hf9FRoe0R_IwQ',
    'CSS | 33. O\'lchov birliklari (Units)':'BAACAgIAAxkBAAIEKmIfEvRx3wU5bUnHp8iKF17u09UiAAK9EwACtNtJS_nj4FujTvbhIwQ',
    'CSS | 34. Foiz (%) o\'lchov birligi':'BAACAgIAAxkBAAIELGIfEyrHYfkvkmpE1Ii2IBGCy9eVAAK_FwACjCZJSyVyZwrYCwgyIwQ',
    'CSS | 35. "em" o\'lchov birligi':'BAACAgIAAxkBAAIELmIfE2JFHQAB2L6SRhAjHeHaK3V6KwAC9hQAApfESEu9HqjrBT-9VyME',
    'CSS | 36. rem o\'lchov birligi':'BAACAgIAAxkBAAIEMGIfE5jars5vkhgKRJCvnAbDGe0sAAIbEwACEu9JS7PUaaNDh8QPIwQ',
    'CSS | 37. Viewport o\'lchov birligi':'BAACAgIAAxkBAAIEMmIfE8RzcCBrM7NLsU3u-LPPAAHBHAACQBkAAoBeUEsbN-aH8K9qYiME',
    'CSS | 38. Units yordamida loyihani yaxshilab olish':'BAACAgIAAxkBAAIENmIfFAABjCBHpxoSZ98Zu-8e0cr5hwACRBQAArTbSUsIq_ZfTyj4qCME',
    'CSS | 39. Responsive Web Design (RWD)':'BAACAgIAAxkBAAIEOGIfFBzThfV0BRThG-icpUWGUbLoAAJ2FgACOllYS_J5XM5UFuFRIwQ',
    'CSS | 40. Media queries':'BAACAgIAAxkBAAIEOmIfFEPK6lZVKpoYASC_T6hrershAAJAFAACq8FQS3HdTNZNp4m7IwQ',
    'CSS | 41. Breakpoints':'BAACAgIAAxkBAAIEPGIfFHHy77PiNxjjoWhJtZL_eubiAALRFAACNSDBS4v2m869FuOTIwQ',
    'CSS | 42. RWD yordamida loyihani yaxshilash (1-qism)':'BAACAgIAAxkBAAIEPmIfFJqzfwNnPLtiryxbzHjd2rAJAALkEgACLSiBS6ctwe5ghS05IwQ',
    'CSS | 43. RWD yordamida loyihani yaxshilash (2-qism)':'BAACAgIAAxkBAAIEQGIfFMWtiRdo_KYfyO4Bn-hNpAnJAALnEgACMMfBS-w_bsH5ekh_IwQ',
    'CSS | 44. Fonts':'BAACAgIAAxkBAAIEQmIfFPwym5uDPMTpPWkeUA79FBYbAAI6FwACMn9YSE3N_PUdhYYJIwQ',
    'CSS | 45. Yangi font qo\'shish':'BAACAgIAAxkBAAIERGIfFSN0qGg_MrujGFjALKXXk31sAAMSAALH5ohLP0A_0LWn9WQjBA',
    'CSS | 46. Local font qo\'shish':'BAACAgIAAxkBAAIERmIfFUQKXu1la0Zrn9zqxvMVNsvLAAIPGAACDPlZSFgdX4VhMaGJIwQ',
    'CSS | 47. Font xossalari':'BAACAgIAAxkBAAIESGIfFXG5qkEz9j58rCOVoPyhhksxAAJaGQACiCRZSAaQh2OBkBviIwQ',
    'CSS | 48. Fonts yordamida loyihani yaxshilab olish':'BAACAgIAAxkBAAIESmIfFY-M8yBMxSc5rrZAx4aXJ8VeAAKCFwAC2bhYSN6q00MR8z2gIwQ',
    'CSS | 49. 2D transforms':'BAACAgIAAxkBAAIETGIfFbrohiG5OPr0FAUU0jVyj7GwAAKgFwACddvISzIRH-agXfWcIwQ',
    'CSS | 50. 3D transforms':'BAACAgIAAxkBAAIETmIfFdyaj2KGAAEFnii0NlHGUKl-jgACohcAAnXbyEtrWY1qkgZZPSME',
    'CSS | 51. Transitions':'BAACAgIAAxkBAAIEUGIfFfnvIUuP5XhcY-kRoJtetR0rAAIhGgACkbBZSC5E5wG5SHvZIwQ',
    'CSS | 52. Animations (1-qism)':'BAACAgIAAxkBAAIEUmIfFiDbWHGnNFCbJzzqcpFHT6sOAALwEQACXiUQS-oY31OoYZV9IwQ',
    'CSS | 53. Animations (2-qism)':'BAACAgIAAxkBAAIEVGIfFj5xq4QHkM0-xR7FmBp8MOTJAAKFFQAC_bIJS3s_8nB9DKMDIwQ',
    'CSS | 54. CSS Advanced yordamida loyihani yaxshilash':'BAACAgIAAxkBAAIEVmIfFlP7encbOffOMMaIWu7uz2KBAAI7GQACDPlZSBO8w1oEgSILIwQ',
    'CSS | 55. Flexbox: asoslari va terminlari':'BAACAgIAAxkBAAIEWGIfFn9kflFtUzbLEt2g5ZZ6EWX_AAJWFQAChGNYSGkr8MJM5n5vIwQ',
    'CSS | 56. Flexbox: flex-direction, flex-wrap, flex-flow va justify-content':'BAACAgIAAxkBAAIEWmIfFphmnVujRODTSKpOvt0Tcnw6AAKgFwACRatgSNI7CttTuh14IwQ',
    'CSS | 57. Flexbox: align-items va align-content':'BAACAgIAAxkBAAIEXGIfFr2drDRhV3anWjX-FJU7gTpmAALCGAACHMJYSEbMBgvXQ0DZIwQ',
    'CSS | 58. Flexbox: order, flex-grow va flex-shrink':'BAACAgIAAxkBAAIEXmIfFt_W6EVHRVFR3nn9WbrzLsGFAAJdFwACQeNgSMUPJ_lZkLLdIwQ',
    'CSS | 59. Flexbox: flex-basis, flex va align-self':'BAACAgIAAxkBAAIEYGIfFvnG9LEogRvOzGhfZyGFRxs4AAKkEgACsdVgSEssu9d6-XpGIwQ',
    'CSS | 60. Flexbox yordamida loyihani yaxshilash':'BAACAgIAAxkBAAIEYmIfFx83ShSfFXNg7WggAAFSh5-vHgACxxYAAvtOWEhNH3sFvvhwrCME',
    'CSS | 61. CSS Grid':'BAACAgIAAxkBAAIEZGIfF0RpsCntNyeW8pzQx6gVT_uDAAKXFQACVHlhSA8ggvf800gzIwQ',
    'CSS | 62. Best practices':'BAACAgIAAxkBAAIEZmIfF2K2t8yUcgiQy5YiEEMmgV3KAAJmGAACReBYSKUgijZXC4f8IwQ',
    'CSS | 63. Loyihani yakunlash. Kurs yakuni':'BAACAgIAAxkBAAIEaGIfF5NId8iVg0eg0prT4sfufdbMAALtFwACE4pYSLjCj7Ig8jsUIwQ',

}