

DJANGO = {
    '#00 Python Django | Kirish darsi': 'BAACAgIAAxkBAAIF_mIhnYsTkaDaqwX6BnrFZox6EiM4AAJbFQACkIZIS7qA71CVEswoIwQ',
    '#01 Python Django | Command Prompt': "BAACAgIAAxkBAAIGAAFiIZ4yQ3RTLLUUFKbn8RmEL9XEpwACWBIAAv6YKEp-LBjDDd6cMCME",
    '#02 Python Django | Python va PyCharm o\'rnatamiz': "BAACAgIAAxkBAAIGAmIhnlXLgkCqW-0J5iDcYk6u572yAAK_HAACW2ooSjXmTlHq2_LlIwQ",
    '#03 Python Django | pipenv va Django': "BAACAgIAAxkBAAIGBGIhnqL8F_rWAi9FdOE9hCFxoPR5AAKEFAACu20xSnyz8tp9veYKIwQ",
    '#04 Python Django | Project va App': "BAACAgIAAxkBAAIGBmIhntLPYmxpQTZcyoFzI4eHsGC2AALtDwACP1AwSu7u6XfhiXVxIwQ",
    '#05 Python Django | MVT Model-View-Template': "BAACAgIAAxkBAAIGCGIhnu9Tocud-2vvhuJgCNliUwUFAAI_EQACYUZYS5s8P5bC0Z1SIwQ",
    '#06 Python Django | "Hello, World!"': "BAACAgIAAxkBAAIGCmIhnwzthjOlU9n8tycQh3k2NsJTAAJdEwAC3My4SpUteeDx2IbOIwQ",
    '#07 Python Django | Template yaratish': "BAACAgIAAxkBAAIGDGIhnzGTcUUnCt7SpQ5c_LKzQJm-AAL3DwACP1AwSij42VoLdibNIwQ",
    '#08 Python Django | Tayanch Template': "BAACAgIAAxkBAAIGDmIhn1fGo9PHE4u2D331Q0p5gmb3AALnEgACIGgxSmyw66STaNGzIwQ",
    '#09 Python Django | Loyihani Heroku Serverga Yuklash': "BAACAgIAAxkBAAIGEGIhn3aaVLLMAAER3Y6ctcc0iWLs_QACeRcAAscCaUvVCP_MvBO28yME",
    '#10 Python Django | Birinchi Modelimiz': "BAACAgIAAxkBAAIGEmIhn5OKkh0MfJukzobnOJ5zVitNAAIIFwACF2JwSyhxNskatM-XIwQ",
    '#11 Python Django | Model-View-Template': "BAACAgIAAxkBAAIGFGIhn712m0la6xWMz4ayq37R7iFuAAL2EQACLXdwS4pRS19pMOtZIwQ",
    '#XX Python Django | HTML va CSS nima?': "BAACAgIAAxkBAAIGFmIhn9ls_5cX2uhegRSjt7E8FSuxAAIlGAACzQpwS0RDFuyzOI4rIwQ",
    '#12 Python Django | Blog yaratamiz. 1-qism': "BAACAgIAAxkBAAIGGGIhoAAB0lOBMjHgPQSqhr1d-dbcyAACMBsAAubTcEtByo8T1xqKAiME",
    '#13 Python Django | Blog yaratamiz. 2-qism': "BAACAgIAAxkBAAIGGmIhoB75uSG65mKp-gqeMtmYfdyAAAIdFgAC45xYS1ay8gTF7n_7IwQ",
    '#14 Python Django | Blog yaratamiz. 3-qism': "BAACAgIAAxkBAAIGHGIhoDohC7f6WiLU_FJ6UTBDTnwFAAJtFAAC2UzBSi5-83aq0yPnIwQ",
    '#15 Python Django | Blog yaratamiz. 4-qism': "BAACAgIAAxkBAAIGHmIhoQuxanoopGGIFRf0qCOYsdz4AAJkEAACX6TASn_AziiooO2lIwQ",
    '#16 Python Django | Blog2.0. 1-qism: Kirish': "BAACAgIAAxkBAAIGIGIhoYqSGXntXiEkmBd_51iFp7tVAAKaEwACkA8gS9EErIcD8ENJIwQ",
    '#17 Python Django | Blog2.0. 2-qism. Custom User Model.': "BAACAgIAAxkBAAIGI2IhocP1GvqSQ_wf2eTrK6E62piaAAKMEgACRJggS_-CqqtJ6NLPIwQ",
    '#18 Python Django | Blog2.0. 3-qism. Foydalanuvchilar bilan ishlash': "BAACAgIAAxkBAAIGJWIhodog-jUWrOgFmSa0RItKruDGAAJ2FgACNcXYS7vVNxNx5bKjIwQ",
    '#19 Python Django | Blog2.0. 4-qism. Bootstrap': "BAACAgIAAxkBAAIGJ2IhofMPnRnMoV1wlg_C6dzew8snAALYFwACadrYS1p9iMwIZaZlIwQ",
    '#20 Python Django | Blog2.0. 5-qism. Password reset': "BAACAgIAAxkBAAIGKWIhopmvn8dj7zqE0FqbYGxn0xDyAAJUFwACknIgS2pLLwABQhncVyME",
    '#21 Python Django | Blog2.0. 6-qism. Postlar qo\'shish': "BAACAgIAAxkBAAIGK2IhorhtgFETisV8bvqQFOeQit51AAJnFAAC-q3ZS09Wm921CRtgIwQ",
    '#22 Python Django | Blog2.0. 7-qism. Avtorizasiya': "BAACAgIAAxkBAAIGLWIhotxgj4juZDJq7RewVIeGg12TAAL8FAACXbPZS4dpl5RLLaGSIwQ",
    '#23 Python Django | Blog2.0. 8-qism. Matn Muharriri': "BAACAgIAAxkBAAIGL2IhowYxTG0rEtt8FLBzXDPaTnuxAAIeFAACp4vQS78sVNWR7HgpIwQ",
    '#24 Python Django | Blog2.0. 9-qism. Izohlar': "BAACAgIAAxkBAAIGMWIhox3KaQXlmZFCIPV2f2p8PhfaAAJlFgACn0DYS4DgQmu-HDT0IwQ",
    '#25 Python Django | Blog2.0. 10-qism. Deploy': "BAACAgIAAxkBAAIGM2Iho0CMTwpasg8tlLtBCqOF5TeIAAJTEwACuqTRS72PPRnKch1XIwQ",
}
