PYTHON = {
    '📹 #00 Python Darslari | Kirish so\'z': "BAACAgIAAxkBAAIGVGIhqv6Vt4VLIHtAkrgTdskDyJowAAJHDQAC7yywSfAF7YL0TfJ2IwQ",
    '📹 #00 Python Darslari | Darslarni qanday o\'zlashtiramiz?': "BAACAgIAAxkBAAIGVmIhrU-2rMk9kWZX7_5BsEYpkSXkAALpCgACwy-xSYQMMSPu4zv4IwQ",
    '📹 #01 Python Darslari | Anaconda o\'rnatamiz': "BAACAgIAAxkBAAIGWGIhrWwd9twmzohQHteoT-9DNaLsAAJSDQAC7yywSd-UtW2pneN0IwQ",
    '📹 #02 Python Darslari | Birinchi Dasturimiz': "BAACAgIAAxkBAAIGWmIhrYcXHt8vn7W86BNag-RxPXboAALzCgACwy-xSezEFV7KjZHeIwQ",
    '📹 #03 Python Darslari | print(), Arifmetik amallar va Sinteks': "BAACAgIAAxkBAAIGXGIhraXCtkO_AAFWMATb9nrfPjA8iwACYA0AAu8ssElpNgx1s1TkPCME",
    '📹 #04 Python Darslari | O\'zgaruvchilar (Variables)': "BAACAgIAAxkBAAIGXmIhrcjgoqqOV-gxadFhYDdWwsYeAALXBgACu5j4SWv1m_pGZjaZIwQ",
    "📹 #05 Python Darslari | Matn bilan ishlash (Strings)": "BAACAgIAAxkBAAIGYGIhrgHEup7eKUlXTGtTK6Fnuo-OAALUBgACu5j4SRahMQE2ZWrDIwQ",
    '📹 #06 Python Darslari | Sonlar bilan ishlash': "BAACAgIAAxkBAAIGYmIhriOPLBx6m9VWAsJtq8qP-i6DAALbBgACu5j4STAxQ26ZO7wmIwQ",
    '📹 #07 Python Darslari | Lists (Ro\'yxatlar)': "BAACAgIAAxkBAAIGZGIhrnLUfzq1RPlZQ5VA97IgpATmAALZBgACu5j4SYBbUUSCZ43qIwQ",
    '📹 #08 Python Darslari | Ro\'yxat bilan ishlash. O\'zgarmas': "BAACAgIAAxkBAAIGZmIhrqUuvRy7lMs6CnVUJVNCXuriAALVBgACu5j4SeGNNwvhLeBeIwQ",
    '📹 #09 Python Darslari | for tsikli bilan tanishamiz': "BAACAgIAAxkBAAIGaGIhrspjOXmQiQ-vn1_7yUDYU8e7AALaBgACu5j4SSs0n4t0DieZIwQ",
    '📹 #10 Python Darslari | if-else shartlari va tarmoqlanish': "BAACAgIAAxkBAAIGamIhrtoPQpS5E2iNblIfnOl96tugAALxCgACI9_gSSd3GEVJHiOIIwQ",
    '📹 #11 Python Darslari | if-elif-else': "BAACAgIAAxkBAAIGbGIhsFpJxY6k63JXZ5NEeM6XVumPAAIPCQACL2dISi113REGRxi2IwQ",
    '📹 #12 Python Darslari | Eng ko\'p uchraydigan xatolar': "BAACAgIAAxkBAAIGbmIhsIPbDkJw21LZ9znZAUHfsGqBAALYCAACn2QISvfLaoEvGGL_IwQ",
    '📹 #13 Python Darslari | GitHub bilan tanishuv': "BAACAgIAAxkBAAIGemIhsMjCyrTBTUceIwyJo4PBJT1tAAKzCAACoqcwSk-mBGaweAdiIwQ",
    '📹 #14 Python Darslari | Lug\'at (Dictionary)': "BAACAgIAAxkBAAIGfGIhsOWveiYT-NEkvsQ-l7No8fGUAAJmCQACzO9hSgQt61nWiq1SIwQ",
    '📹 #15 Python Darslari | Lug\'at bilan ishlaymiz': "BAACAgIAAxkBAAIGfmIhsP2DtWjktPjfZmG_Xf3U6WppAALzCQACMKVwStvI2SJx_ez9IwQ",
    '📹 #16 Python Darslari | Nestin': "BAACAgIAAxkBAAIGgGIhsRImmvMjKVDsTwbK06OIzmmbAALvCQACMKVwSoM16UepVl8OIwQ",
    '📹 #17 Python Darslari | While tsikli': "BAACAgIAAxkBAAIGgmIhsSbU4JQ2VDsuLJn9qTJefYr0AAI3CAACrqWZSo4JsNEYN7XRIwQ",
    '📹 #18 Python Darslari | While, Ro\'yxatlar va Lug\'atlar': "BAACAgIAAxkBAAIGhGIhsTcpXQKkni-z-NvNRwAB1U-XoAACYwkAAvqOuErSLLB4tLV-xCME",
    '📹 #19 Python Darslari | Funksiya': "BAACAgIAAxkBAAIGhmIhsVWEgjeV3izvTnJG44ztGmviAAJCDQACyvPhShOjaXT7PeBGIwQ",
    '📹 #20 Python Darslari | Funksiyadan qiymat qaytaris': "BAACAgIAAxkBAAIGiGIhtB6erguQQ2bOSkym8PLB5ArOAAKfCQACjmPoSoVS2bCJnEVyIwQ",
    '📹 #21 Python Darslari | Funksiyaga ro\'yxat uzatish': "BAACAgIAAxkBAAIGimIhtENWIBqvyvIvmwHW1icpmhXRAAKrCQACpJ8QS_lyZjua8Bz-IwQ",
    '📹 #22 Python Darslari | Moslashuvchan funksiyalar': "BAACAgIAAxkBAAIGjGIhtF10oInw10_z4-w3Wd_XkOo_AAKACgACfPZISxITWBRuKJMyIwQ",
    '📹 #23 Python Darslari | Modullar': "BAACAgIAAxkBAAIGjmIhtHhs90vA1QobOjYEkevX92f_AAJ9CgACfPZISxXQWgP5ukiDIwQ",
    '📹 #24 Python Darslari | Funksiya. So\'ngso\'z.': "BAACAgIAAxkBAAIGkGIhtJPsL0-PA3zMWDKZCl4xpprcAAJoCgACLwOAS5d1ORC-9NeVIwQ",
    '📹 #25 Python Darslari | Son topish o\'yini. 1-qism': "BAACAgIAAxkBAAIGkmIhtK_ZRXQwmKesfPkFuAxi6EF5AALDCAACvZqoS6qn1GhEskRxIwQ",
    '📹 #26 Python Darslari | So\'z topish o\'yini. 1-qism. Tanishuv': "BAACAgIAAxkBAAIGlGIhtNfU39npsdMC2DtDMvt8QRHAAAI5DAACOpXRS-cSGRByTweZIwQ",
    '📹 #27 Python Darslari | Kirill-Lotin Transliterator Bot. 1-qism': "BAACAgIAAxkBAAIGlmIhtPJknYdm60Ek6D3Gd2Ps-2QnAALDCgACmvsJSGCgiutUFTJtIwQ",
    '📹 Object Oriented Dasturlash nima?': "BAACAgIAAxkBAAIGmGIhtTKDY6K9ZO7wDPiWGzVwpwkiAAKECQACq1IgSF8Uri5lkX8hIwQ",
    '📹 #28 Python Darslari | Object Oriented Dasturash. Klass va Obyekt': "BAACAgIAAxkBAAIGmmIhtWvO9Vy9wbN96Dg3sXF4j3ExAAIDCwACydtZSIcXTkrRhJYhIwQ",
    '📹 #29 Python Darslari | Object Oriented Dasturash. Obyektlar bilan ishlash': "BAACAgIAAxkBAAIGnGIhtYxIDGADV_WlNOXpDSaBhr1sAAJWCQAClRmJSNNWBpE0Zjy3IwQ",
    '📹 #30 Python Darslari | Object Oriented Dasturash. Vorislik va Polimorfizm': "BAACAgIAAxkBAAIGnmIhtZ7Ww3VKiMAfr8-J2We-MPskAAJuCQACSeWhSOO1tA3HY8nDIwQ",
    '📹 #31 Python Darslari | Object Oriented Dasturash. Inkapsulyatsiya. Klassga xos xususiyat va metodlar': "BAACAgIAAxkBAAIGoGIhtbufRvndQ2i1WiTOxzh4S5aEAAIUDAACCKTRSIrIvWUuKViiIwQ",
    '📹 #32 Python Darslari | Object Oriented Dasturash. Dunder Metodlar. 2-qism': "BAACAgIAAxkBAAIGomIhtfTGuPRjl_Cy49mN1s4Nk_UVAAKQDQACXVPgSIMxN_04O0PoIwQ",
    '📹 #33 Python Darslari | Fayllar bilan ishlash. Pickle.': "BAACAgIAAxkBAAIGpGIhthrBwzClv8fHnnVPt8RAKupgAAIUDAACFYcoSfkkCRzpTQABLCME",
    '📹 #34 Python Darslari | JSON': "BAACAgIAAxkBAAIGpmIhtlOwEG6UAWt8msgdmpkIc8u9AALdDAAC86dISTdlEP2bOR8NIwQ",
    '📹 #35 Python Darslari | Xatolar bilan Ishlash. try-except': "BAACAgIAAxkBAAIGqGIhtmhAG6Pqg0zEeXR7lIQDCWAmAAKUCQAC8eR4SdrpZcsPeFYLIwQ",
    '📹 #36 Python Darslari | Funksiyalarni tekshirish. unittest moduli': "BAACAgIAAxkBAAIGqmIhtnscyVI_KEfGOme9Nn13ZN85AAJcCgACv2OgSUXsK5E3Z_fmIwQ",
    '📹 #37 Python Darslari | Klasslarni tekshirish.': "BAACAgIAAxkBAAIGrGIhtripwg6pRUnbsJleHZMsSw60AAKuDgAC05ngSVgD2qxKNUzLIwQ",
    '📹 #38 Python Darslari | Python Standart Kutubxonasi': "BAACAgIAAxkBAAIGrmIhttU1szy4wcMBOapqteqHGn26AALADAACi8VBSpDzSeMVsEl3IwQ",
    '📹 #39 Python Darslari | Python Tashqi Kutubxonasi PyPi.org': "BAACAgIAAxkBAAIGsGIhtu-CtgMhciF4tsH-J5XxkGAMAAJ5CwACUmBhSnoqkex02FksIwQ",
    '📹 #40 Python Darslari | Soʻngsoʻz': "BAACAgIAAxkBAAIGsmIhtw7zjgitAAHMeSt8KtFri3E_TwACsgsAAsYAAXlK8r8kB39b-l0jBA",

}
