
TGBOT = {
    '#00 MUKAMMAL TELEGRAM BOT | KURS BILAN TANISHUV': "BAACAgIAAxkBAAIGN2IhpuOA1fYeUlnATEKbCyybjiqpAAI7FQACELegSpEb5pp6f0h2IwQ",
    '#01 MUKAMMAL TELEGRAM BOT | KERAKLI DASTURLAR': "BAACAgIAAxkBAAIGOWIhpyH6Tj5FvejJ9mxN_vFLG5oZAAK6FAACVc8gSrOPMgkqz1EuIwQ",
    '#02 MUKAMMAL TELEGRAM BOT | METODOLOGIYA': "BAACAgIAAxkBAAIGO2IhpzfBXO0_EtZn0X7xswSKji1KAALdEgAC6IuhShtfCzpo3vfAIwQ",
    '#03 MUKAMMAL TELEGRAM BOT | botFather': "BAACAgIAAxkBAAIGPWIhp1A-BWvQh1lUzYfJWBpOHIfjAALVEwAC7dGpSjvwafCUMd2VIwQ",
    '#04 MUKAMMAL TELEGRAM BOT | aiogram': "BAACAgIAAxkBAAIGP2Ihp2t_ygjJtoKnaXneoTsFO6cjAALfEwACAXuZSlDltIxXVox8IwQ",
    '#05 MUKAMMAL TELEGRAM BOT | wikibot': "BAACAgIAAxkBAAIGQWIhp4fRhg9fGSzSdq2uU00r01UlAALjEwACAXuZSslGgB6d2RZAIwQ",
    '#06 MUKAMMAL TELEGRAM BOT | API nima?': "BAACAgIAAxkBAAIGQ2Ihp5-6yYri3rp6E6w2VrMa5CR2AAJaEwACRjOgSpDZR9AuQS66IwQ",
    '#07 MUKAMMAL TELEGRAM BOT | Bot uchun qiziqarli API topamiz': "BAACAgIAAxkBAAIGRWIhp8NrXiJKJQ1On0SW61dIIxXTAAJbEwACRjOgSi8ogC-3OYfFIwQ",
    '#08 MUKAMMAL TELEGRAM BOT | Pythonda API bilan ishlash': "BAACAgIAAxkBAAIGR2Ihp9v7WgG6xKvpjb8tI83f9pfIAAJCFQACmipoSubn70XPAAEZKSME",
    '#09 MUKAMMAL TELEGRAM BOT | speakEnglish bot': "BAACAgIAAxkBAAIGSWIhp_INEfpeXWl9aAABUKYb_Yh6nAAC1xEAAuXJwUrdONT4cNxSASME",
    '#10 MUKAMMAL TELEGRAM BOT | imloBot. 1-qism: So\'zlarni tekshirish': "BAACAgIAAxkBAAIGS2IhqAliwlgfzU7oChjmqf9Ht3EcAAK-FAACStCYStH9rRhkcnaWIwQ",
    '#11 MUKAMMAL TELEGRAM BOT | imloBot. 2-qism: Bot dasturi': "BAACAgIAAxkBAAIGTWIhqCnoU0zB9lPv1FLBV2knXGVXAAIIEgAC9xfASgwbunOVOWR7IwQ",
    '#12 MUKAMMAL TELEGRAM BOT | Botni serverga yuklash': "BAACAgIAAxkBAAIGT2IhqEkPvN2-2TyMzUcEDazfD3uAAAJ8FAACHZvASq9KG7EtH3HiIwQ",
    '#13 MUKAMMAL TELEGRAM BOT | DIQQAT, AKSIYA!': "BAACAgIAAxkBAAIGUWIhqGOB5a-khf01afI9a-oJ9S8DAALWGAACT-nJSrhEAqBjXNgEIwQ",

}
